# Generated by Django 5.0.4 on 2024-04-23 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('task', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
                ('np', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(280)])),
                ('slots', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(96)])),
                ('simulation', models.CharField(choices=[('guam', 'Guam'), ('katrina', 'Katrina'), ('gustav', 'Gustav')], max_length=8)),
            ],
        ),
    ]
