# Generated by Django 5.0.4 on 2024-04-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='simulation',
            field=models.CharField(choices=[('Guam', 'Guam'), ('Katrina', 'Katrina'), ('Gustav', 'Gustav')], max_length=10),
        ),
    ]
