apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    nvidia.network-operator.revision: "2193006554"
  creationTimestamp: "2024-04-12T16:16:54Z"
  generation: 1
  labels:
    app: mofed-ubuntu22.04
    nvidia.com/ofed-driver: ""
    nvidia.network-operator.state: state-OFED
  name: mofed-ubuntu22.04-ds
  namespace: nvidia-operator
  ownerReferences:
  - apiVersion: mellanox.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: NicClusterPolicy
    name: nic-cluster-policy
    uid: 5c0b8f43-456b-42cd-a9e1-259673f0bc34
  resourceVersion: "31687075"
  uid: 021eb708-9945-4830-8b06-c44c2ea37cf2
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mofed-ubuntu22.04
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mofed-ubuntu22.04
        nvidia.com/ofed-driver: ""
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: nvidia.com/ofed-driver
                operator: Exists
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: CREATE_IFNAMES_UDEV
          value: "true"
        image: nvcr.io/nvidia/mellanox/doca-driver:24.01-0.3.3.1.3-ubuntu22.04-amd64
        imagePullPolicy: IfNotPresent
        resources:  
          limits:  
            cpu: "4"  
            memory: "4Gi"  
          requests:  
            cpu: "4"  
            memory: "4Gi"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - lsmod | grep mlx5_core
          failureThreshold: 1
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: mofed-container
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - lsmod | grep mlx5_core
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
          privileged: true
          seLinuxOptions:
            level: s0
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - ls /.driver-ready
          failureThreshold: 60
          initialDelaySeconds: 10
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/mellanox/drivers
          mountPropagation: Bidirectional
          name: run-mlnx-ofed
        - mountPath: /etc/network
          name: etc-network
        - mountPath: /host/etc
          name: host-etc
        - mountPath: /host/usr
          name: host-usr
        - mountPath: /host/lib/udev
          name: host-udev
        - mountPath: /run/udev
          name: host-run-udev
          readOnly: true
        - mountPath: /host/lib/modules
          name: host-lib-modules
      dnsPolicy: ClusterFirst
      hostNetwork: true
      initContainers:
      - args:
        - --node-name
        - $(NODE_NAME)
        - --configmap-name
        - ofed-init-container-config
        - --configmap-namespace
        - nvidia-operator
        - --configmap-key
        - config.json
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: ghcr.io/mellanox/network-operator-init-container:v0.0.2
        imagePullPolicy: IfNotPresent
        resources:  
          limits:  
            cpu: "4"  
            memory: "4Gi"  
          requests:  
            cpu: "4"  
            memory: "4Gi"
        name: network-operator-init-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      nodeSelector:
        feature.node.kubernetes.io/pci-15b3.present: "true"
        feature.node.kubernetes.io/system-os_release.ID: ubuntu
        feature.node.kubernetes.io/system-os_release.VERSION_ID: "22.04"
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ofed-driver
      serviceAccountName: ofed-driver
      terminationGracePeriodSeconds: 300
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
      volumes:
      - hostPath:
          path: /run/mellanox/drivers
          type: ""
        name: run-mlnx-ofed
      - hostPath:
          path: /etc/network
          type: ""
        name: etc-network
      - hostPath:
          path: /etc
          type: ""
        name: host-etc
      - hostPath:
          path: /usr
          type: ""
        name: host-usr
      - hostPath:
          path: /lib/udev
          type: ""
        name: host-udev
      - hostPath:
          path: /run/udev
          type: ""
        name: host-run-udev
      - hostPath:
          path: /lib/modules
          type: ""
        name: host-lib-modules
  updateStrategy:
    type: OnDelete
status:
  currentNumberScheduled: 3
  desiredNumberScheduled: 3
  numberMisscheduled: 0
  numberReady: 0
  numberUnavailable: 3
  observedGeneration: 1
  updatedNumberScheduled: 3
