apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: stormbreaker-ui  
spec:
  replicas: 1  
  selector:  
    matchLabels:  
      app: stormbreaker-ui
  template:  
    metadata:  
      labels:  
        app: stormbreaker-ui
        azure.workload.identity/use: "true"
      annotations:
        azure.workload.identity/inject-proxy-sidecar: "true"
    spec:
      serviceAccountName: workload-identity-sa
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - system  
      containers:  
      - name: stormbreaker-ui
        image: stormbreakeracrdc.azurecr.io/misc/ui:1.3
        imagePullPolicy: Always
        env:
          - name: SERVICE_BUS_FQDN
            value: 'dc-sb-test.servicebus.windows.net'
          - name: SERVICE_BUS_QUEUE_DISPATCH
            value: "dcq1dispatch"
          - name: SERVICE_BUS_QUEUE_RUNNING
            value: "dcq1running"
          - name: SERVICE_BUS_QUEUE_DELETE
            value: "dcq1delete"
#        resources:
#          limits:
#            cpu: 2
#            memory: 1Gi
        ports:
        - containerPort: 8501
