apiVersion: v1
kind: Service
metadata:
  name: stormbreaker-api-service
spec:
  selector:
    app: stormbreaker-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stormbreaker-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stormbreaker-api
  template:
    metadata:
      labels:
        app: stormbreaker-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                      - system
      serviceAccount: sa-keda-sb-kubectl
      containers:
        - name: backend
          image: stormbreakeracrdc.azurecr.io/misc/backend:1.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: django-secret
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
