apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: keda-sb-kubectl
rules:
- apiGroups: ["batch.volcano.sh"] 
  resources: ["jobs"]
  verbs: ["get", "watch", "list", "create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-keda-sb-kubectl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-keda
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keda-sb-kubectl
subjects:
- kind: ServiceAccount
  name: sa-keda-sb-kubectl
  namespace: default