apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: stormbreaker-ui  
spec:  
  replicas: 1  
  selector:  
    matchLabels:  
      app: stormbreaker-ui
  template:  
    metadata:  
      labels:  
        app: stormbreaker-ui
    spec:  
      containers:  
      - name: stormbreaker-ui
        image: stormbreakeracrdc.azurecr.io/misc/ui:1.3
        imagePullPolicy: Always
        env:
          - name: SERVICE_BUS_FQDN
            value: 'dc-sb-test.servicebus.windows.net'
          - name: SERVICE_BUS_QUEUE_NAME
            value: "dcq1"
        ports:
        - containerPort: 8501
