apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-nfs-config
data:
  entrypoint.sh: |-
     #!/bin/bash
     # Copyright 2015 The Kubernetes Authors.
     #
     # Licensed under the Apache License, Version 2.0 (the "License");
     # you may not use this file except in compliance with the License.
     # You may obtain a copy of the License at
     #
     #     http://www.apache.org/licenses/LICENSE-2.0
     #
     # Unless required by applicable law or agreed to in writing, software
     # distributed under the License is distributed on an "AS IS" BASIS,
     # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     # See the License for the specific language governing permissions and
     # limitations under the License.
     set -x
     function start()
     {
         # prepare /etc/exports
         # create a filesystem on /dev/nvme0n1
         yum install -y xfsprogs
         mkfs.xfs /dev/nvme0n1
         mkdir /exports/nvme
         mount /dev/nvme0n1 /exports/nvme

         fsid=1
         echo "/exports *(rw,fsid=0,insecure,no_root_squash)" >> /etc/exports
         for i in "$@"; do
              # fsid=0: needed for NFSv4
              echo "/exports/$i *(rw,fsid=$fsid,insecure,no_root_squash)" >> /etc/exports
              # make the directories and mount the disks
              # mkdir /exports/"$i"
              # mount_point=$(df | awk -v var="$i" '$0 ~var {print $1}')
              # mount $mount_point /exports/$i
              
              # create a file to id the filesystem
              touch /exports/$i/this_is_$i
              echo "Serving /exports/$i"
              fsid=$((fsid+1))
          done

          
          # start rpcbind if it is not started yet
          /usr/sbin/rpcinfo 127.0.0.1 > /dev/null; s=$?
          if [ $s -ne 0 ]; then
            echo "Starting rpcbind"
            /usr/sbin/rpcbind -w
          fi

          mount -t nfsd nfds /proc/fs/nfsd

          # -N 4.x: disable NFSv4
          # -V 3: enable NFSv3
          /usr/sbin/rpc.mountd -N 2 -N 3 -V 4 -V 4.1

          /usr/sbin/exportfs -r
          # -G 10 to reduce grace time to 10 seconds (the lowest allowed)
          /usr/sbin/rpc.nfsd -G 10 -N 2 -N 3 -V 4 -V 4.1 2
          /usr/sbin/rpc.statd --no-notify
          echo "NFS started"
      }

      function stop()
      {
          echo "Stopping NFS"

          /usr/sbin/rpc.nfsd 0
          /usr/sbin/exportfs -au
          /usr/sbin/exportfs -f

          kill $( pidof rpc.mountd )
          umount /proc/fs/nfsd
          echo > /etc/exports
          exit 0
      }

      # increase the number of threads for the server
      sed -E -i 's/#(RPCNFSDCOUNT=)(16)/\1256/g' /etc/sysconfig/nfs
      yum install fio

      trap stop TERM

      start "$@"

      # Ugly hack to do nothing and wait for SIGTERM
      while true; do
          sleep 5
      done