kind: Pod
apiVersion: v1
metadata:
  name: podman
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: agentpool
            operator: In
            values:
            - adcirchpc
  containers:
    - image:  stormbreakeracrdc.azurecr.io/hpccm:base-3
      name: podman-in-a-pod
      securityContext:
        privileged: true
        capabilities:
          add: ["IPC_LOCK", "CAP_SYS_ADMIN", "CAP_MKNOD"]
      command:
      - /bin/sh
      - -c
      - |
        apt update ; 
        apt install -y infiniband-diags vim kmod python3-pip
        pip install hpccm
        sleep 360d;
      volumeMounts:
        - name: input
          mountPath: "/mnt/input"
          readOnly: false
        - name: output
          mountPath: "/mnt/output"
          readOnly: false
  volumes:
    - name: input
      persistentVolumeClaim:
        claimName: pvc-input
    - name: output
      persistentVolumeClaim:
        claimName: pvc-output
