# ADCIRC compiled with OpenMPI
# models are accessible on a NFS share
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: lm-mpi-job
spec:
  minAvailable: 3
  schedulerName: volcano
  plugins:
    ssh: []
    svc: []
  tasks:
    - replicas: 1
      name: mpimaster
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec:
          containers:
            - name: mpimaster
              image: stormbreakeracrdc.azurecr.io/adcird-tests:55.dev.openmpi-alpha
              command:
              - /bin/entrypoint.sh
              volumeMounts:
              - name: configmap-volume
                mountPath: /bin/entrypoint.sh
                readOnly: true
                subPath: entrypoint.sh
              - name: input
                mountPath: "/mnt/input"
                readOnly: false
              - name: output
                mountPath: "/mnt/output"
                readOnly: false
              ports:
                - containerPort: 22
                  name: mpijob-port
              workingDir: /root
          volumes:
          - name: configmap-volume
            configMap:
              defaultMode: 0700
              name: cm-adcirc
          - name: input
            persistentVolumeClaim:
              claimName: pvc-input
          - name: output
            persistentVolumeClaim:
              claimName: pvc-output
          restartPolicy: OnFailure
    - replicas: 2
      name: mpiworker
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                    - adcirc
          containers:
            - name: mpimaster
              image: stormbreakeracrdc.azurecr.io/adcird-tests:55.dev.openmpi-alpha
              command:
              - /bin/entrypoint.sh
              volumeMounts:
              - name: cm-adcirc-worker-volume
                mountPath: /bin/entrypoint.sh
                readOnly: true
                subPath: entrypoint.sh
              - name: input
                mountPath: "/mnt/input"
                readOnly: false
              - name: output
                mountPath: "/mnt/output"
                readOnly: false
              ports:
                - containerPort: 22
                  name: mpijob-port
              workingDir: /root
          volumes:
          - name: cm-adcirc-worker-volume
            configMap:
              defaultMode: 0700
              name: cm-adcirc-worker
          - name: input
            persistentVolumeClaim:
              claimName: pvc-input
          - name: output
            persistentVolumeClaim:
              claimName: pvc-output
          restartPolicy: OnFailure
