apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-adcirc
data:
  entrypoint.sh: |-
    #!/usr/bin/bash -l
    mkdir -p /var/run/sshd; /usr/sbin/sshd

    # test with Gustav(2008)
    # https://en.wikipedia.org/wiki/Hurricane_Gustav
    cd /mnt/output/TEST_2
    ./run.sh
    tail -f /mnt/output/TEST_2/padcirc_log.txt
