apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-adcirc
data:
  entrypoint.sh: |-
    #!/usr/bin/bash -l
    TEST_DIR="/mnt/output/TEST_2"
    WORK_DIR="/mnt/input/adcirc-testsuite"
    #TEST_DIR="/mnt/input/adcirc-testsuite/adcirc/adcirc_katrina-2d-parallel/"
    mkdir -p /var/run/sshd; /usr/sbin/sshd

    rm ${TEST_DIR}/*.log
    cd ${TEST_DIR} 
    #./RunSingleTest.sh /usr/bin ${TEST_DIR}
    ./run.sh 
    touch a.txt
    tail -f a.txt
