apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-adcirc-worker
data:
  entrypoint.sh: |-
    #!/usr/bin/bash
    source /opt/spack/share/spack/setup-env.sh
    spack load adcirc
    spack load intel-oneapi-mpi@2021.10.0
    
    ADCIRC_HOME=$(dirname $(which adcirc)|tail -n1)
    SPACK_STAGE=/tmp/root/spack-stage
    
    # for some reason, adcircResultsComparison doesn't get copied 
    # into to the directory where adcirc is ... This fixes that
    find $SPACK_STAGE -name adcircResultsComparison -type f -exec cp {} $ADCIRC_HOME \;
    mkdir -p /var/run/sshd; /usr/sbin/sshd -D
