apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test
spec:
  weight: 1
  reclaimable: false
  capability:
    cpu: 6 # each ADCIRC node has 4 vCPU (standard_d4_v5). 
           # Letting k8s use 1 and the rest for ADCIRC
