apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keda-sb-kubectl
rules:
  - apiGroups: ["batch.volcano.sh"]
    resources: ["jobs", "configmaps"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list", "create"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-keda-sb-kubectl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-keda
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keda-sb-kubectl
subjects:
  - kind: ServiceAccount
    name: sa-keda-sb-kubectl
    namespace: default
