# Generated by Django 5.0.4 on 2024-05-07 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
                ('task', models.CharField(max_length=255)),
                ('np', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(280)])),
                ('slots', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(96)])),
                ('simulation', models.CharField(choices=[('Guam', 'Guam'), ('Katrina', 'Katrina'), ('Gustav', 'Gustav')], max_length=10)),
            ],
        ),
    ]
